In [ ]:
!pip install torch torchvision torchaudio

In [ ]:
!pip show torch # for checking if the library is installed

Name: torch
Version: 2.4.1+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.10/dist-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, fastai, torchaudio, torchvision


# BASIC USAGE

In [ ]:
import torch
#creating a 1dim vector
vector_x = torch.tensor(
    [1,2,3,5,6,8]
)
print(
    vector_x
)

tensor([1, 2, 3, 5, 6, 8])


In [ ]:
#creating a 2*2 matrix
matrix_y = torch.tensor(
    [
        [1,2],
        [3,4]
    ]
)
print(
    matrix_y
)

tensor([[1, 2],
        [3, 4]])


In [ ]:
print("the vector x is of a dimension: ",vector_x.shape)
print("the matrix y is of a dimension: ",matrix_y.shape)

the vector x is of a dimension:  torch.Size([6])
the matrix y is of a dimension:  torch.Size([2, 2])


In [ ]:
# Basic operations
z = vector_x + 10 # add 10 o all vector elements
print(z)

tensor([11, 12, 13, 15, 16, 18])


In [ ]:
# Matrix multiplication
matrix_a = torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
matrix_b = torch.tensor(
    [
        [11,12,13],
        [14,15,16],
        [17,18,19]
    ]
)
matrix_c = matrix_a * matrix_b
print(
    matrix_c # c is the result of the multiplication of matrix a by matrix b
)

tensor([[ 11,  24,  39],
        [ 56,  75,  96],
        [119, 144, 171]])


## TYPES

### floats

In [ ]:
import torch

# Float32 (default)
x = torch.tensor([1.0, 2.0, 3.0])
print(f"Default float type: {x.dtype}")

# Float64 (double precision)
y = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print(f"Double precision: {y.dtype}")

# Float16 (half precision)
z = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
print(f"Half precision: {z.dtype}")

# BFloat16 (brain floating point)
w = torch.tensor([1.0, 2.0, 3.0], dtype=torch.bfloat16)
print(f"BFloat16: {w.dtype}")

Default float type: torch.float32
Double precision: torch.float64
Half precision: torch.float16
BFloat16: torch.bfloat16


### ints

In [ ]:
# Int32 (default integer type)
a = torch.tensor([1, 2, 3])
print(f"Default int type: {a.dtype}")

# Int64 (long)
b = torch.tensor([1, 2, 3], dtype=torch.int64)
print(f"64-bit integer: {b.dtype}")

# Int16 (short)
c = torch.tensor([1, 2, 3], dtype=torch.int16)
print(f"16-bit integer: {c.dtype}")

# Int8
d = torch.tensor([1, 2, 3], dtype=torch.int8)
print(f"8-bit integer: {d.dtype}")

# Uint8 (unsigned 8-bit)
e = torch.tensor([1, 2, 3], dtype=torch.uint8)
print(f"Unsigned 8-bit integer: {e.dtype}")

Default int type: torch.int64
64-bit integer: torch.int64
16-bit integer: torch.int16
8-bit integer: torch.int8
Unsigned 8-bit integer: torch.uint8


### booliens

In [ ]:
# Boolean
f = torch.tensor([True, False, True])
print(f"Boolean type: {f.dtype}")

# Create boolean tensor from comparison
g = torch.tensor([1, 2, 3]) > 1
print(f"Result of comparison: {g}")
print(f"Type of comparison result: {g.dtype}")

Boolean type: torch.bool
Result of comparison: tensor([False,  True,  True])
Type of comparison result: torch.bool


### complex

In [ ]:
# Complex64
h = torch.tensor([1+2j, 3+4j], dtype=torch.complex64)
print(f"Complex64 type: {h.dtype}")

# Complex128
i = torch.tensor([1+2j, 3+4j], dtype=torch.complex128)
print(f"Complex128 type: {i.dtype}")

Complex64 type: torch.complex64
Complex128 type: torch.complex128


## conversion

In [ ]:
# Original tensor
original = torch.tensor([1.5, 2.5, 3.5])
print(f"Original: {original} (dtype: {original.dtype})")

# Convert to int32
int_tensor = original.to(torch.int32)
print(f"To int32: {int_tensor} (dtype: {int_tensor.dtype})")

# Convert to float64
double_tensor = original.double()
print(f"To float64: {double_tensor} (dtype: {double_tensor.dtype})")

# Convert to uint8
uint8_tensor = original.to(torch.uint8)
print(f"To uint8: {uint8_tensor} (dtype: {uint8_tensor.dtype})")

Original: tensor([1.5000, 2.5000, 3.5000]) (dtype: torch.float32)
To int32: tensor([1, 2, 3], dtype=torch.int32) (dtype: torch.int32)
To float64: tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64) (dtype: torch.float64)
To uint8: tensor([1, 2, 3], dtype=torch.uint8) (dtype: torch.uint8)


In [ ]:
# Check default types
print(f"Default float type: {torch.get_default_dtype()}")

# Change default float type
torch.set_default_dtype(torch.float64)
print(f"New default float type: {torch.get_default_dtype()}")

# Create a new tensor to verify
new_tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"New tensor dtype: {new_tensor.dtype}")

# Reset to default
torch.set_default_dtype(torch.float32)

Default float type: torch.float32
New default float type: torch.float64
New tensor dtype: torch.float64


## OPERATIONS

1. Creating Vectors and Matrices

In [ ]:
# Create a vector
v = torch.tensor([1, 2, 3, 4, 5])
print("Vector v:", v)

# Create a matrix
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Matrix A:")
print(A)

# Create a 2x3 matrix of ones
B = torch.ones(2, 3)
print("Matrix B:")
print(B)

# Create a 3x3 identity matrix
I = torch.eye(3)
print("Identity matrix I:")
print(I)

Vector v: tensor([1, 2, 3, 4, 5])
Matrix A:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Matrix B:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Identity matrix I:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


2. Vector Operations

In [ ]:
# Vector addition
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])
v_sum = v1 + v2
print("v1 + v2 =", v_sum)

# Scalar multiplication
scalar = 2
v_scaled = scalar * v1
print("2 * v1 =", v_scaled)

# Dot product
dot_product = torch.dot(v1, v2)
print("v1 · v2 =", dot_product)

# Vector norm (magnitude)
norm = torch.norm(v1.to(
    torch.float64
))
print("||v1|| =", norm)

# Normalize a vector
v_normalized = v1 / norm
print("Normalized v1:", v_normalized)

v1 + v2 = tensor([5, 7, 9])
2 * v1 = tensor([2, 4, 6])
v1 · v2 = tensor(32)
||v1|| = tensor(3.7417, dtype=torch.float64)
Normalized v1: tensor([0.2673, 0.5345, 0.8018], dtype=torch.float64)


3. Matrix Operations

In [ ]:
# Matrix addition
C = torch.tensor([[1, 2], [3, 4]])
D = torch.tensor([[5, 6], [7, 8]])
M_sum = C + D
print("C + D:")
print(M_sum)

# Matrix multiplication
M_product = torch.matmul(C, D)
print("C * D:")
print(M_product)

# Element-wise multiplication
M_element_wise = C * D
print("C .* D (element-wise):")
print(M_element_wise)

# Matrix transpose
C_transpose = C.t()
print("C^T (transpose of C):")
print(C_transpose)

# Matrix inverse
C_inv = torch.inverse(C.to(torch.float64))
print("C^-1 (inverse of C):")
print(C_inv)

# Verify inverse
I = torch.matmul(C.to(
    torch.float64
), C_inv)
print("C * C^-1 (should be close to identity):")
print(I)

C + D:
tensor([[ 6,  8],
        [10, 12]])
C * D:
tensor([[19, 22],
        [43, 50]])
C .* D (element-wise):
tensor([[ 5, 12],
        [21, 32]])
C^T (transpose of C):
tensor([[1, 3],
        [2, 4]])
C^-1 (inverse of C):
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]], dtype=torch.float64)
C * C^-1 (should be close to identity):
tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)


4. Solving Linear Systems

In [ ]:
# Define matrix A and vector b
A = torch.tensor([
      [2, 1],
      [1, 3]
    ], dtype=torch.float)
b = torch.tensor([4, 5], dtype=torch.float)
"""
system of equations:
2x + 1y = 4
x  + 3y = 5
"""
# Solve the system Ax = b
x = torch.linalg.solve(A, b)
print("Solution to Ax = b:")
print(x)

# Verify the solution
b_check = torch.matmul(A, x)
print("A * x (should be close to b):")
print(b_check)

Solution to Ax = b:
tensor([1.4000, 1.2000])
A * x (should be close to b):
tensor([4., 5.])


## Complex Numbers

2. Creating Complex Tensors

In [ ]:
# Create a complex tensor from a list of complex numbers
c1 = torch.tensor([1+2j, 3-4j, 5+6j])
print("c1:", c1)
print("c1 dtype:", c1.dtype)

# Create a complex tensor from real and imaginary parts
real = torch.tensor([1., 2., 3.])
imag = torch.tensor([4., 5., 6.])
c2 = torch.complex(real, imag)
print("c2:", c2)
print("c2 dtype:", c2.dtype)

# Create a complex tensor with specific dtype
c3 = torch.tensor([1+2j, 3-4j, 5+6j], dtype=torch.complex128)
print("c3:", c3)
print("c3 dtype:", c3.dtype)

# Create a complex tensor from polar coordinates
magnitude = torch.tensor([1., 2., 3.])
angle = torch.tensor([0., torch.pi/2, torch.pi])
c4 = torch.polar(magnitude, angle)
print("c4:", c4)
print("c4 dtype:", c4.dtype)

c1: tensor([1.+2.j, 3.-4.j, 5.+6.j])
c1 dtype: torch.complex64
c2: tensor([1.+4.j, 2.+5.j, 3.+6.j])
c2 dtype: torch.complex64
c3: tensor([1.+2.j, 3.-4.j, 5.+6.j], dtype=torch.complex128)
c3 dtype: torch.complex128
c4: tensor([ 1.0000e+00+0.0000e+00j, -8.7423e-08+2.0000e+00j,
        -3.0000e+00-2.6227e-07j])
c4 dtype: torch.complex64


3. Accessing Real and Imaginary Parts

In [ ]:
c = torch.tensor([1+2j, 3-4j, 5+6j])

# Access real part
print("Real part:", c.real)

# Access imaginary part
print("Imaginary part:", c.imag)

# Access magnitude (absolute value)
print("Magnitude:", c.abs())

# Access phase angle
print("Phase angle:", c.angle())

Real part: tensor([1., 3., 5.])
Imaginary part: tensor([ 2., -4.,  6.])
Magnitude: tensor([2.2361, 5.0000, 7.8102])
Phase angle: tensor([ 1.1071, -0.9273,  0.8761])


4. Basic Operations with Complex Numbers

In [ ]:
a = torch.tensor([1+2j, 3-4j])
b = torch.tensor([5+6j, 7-8j])

# Addition
print("a + b =", a + b)

# Subtraction
print("a - b =", a - b)

# Multiplication
print("a * b =", a * b)

# Division
print("a / b =", a / b)

# Power
print("a ** 2 =", a ** 2)

# Conjugate
print("Conjugate of a:", a.conj())

# Exponential
print("exp(a) =", torch.exp(a))

# Natural logarithm
print("log(a) =", torch.log(a))

a + b = tensor([ 6.+8.j, 10.-12.j])
a - b = tensor([-4.-4.j, -4.+4.j])
a * b = tensor([ -7.+16.j, -11.-52.j])
a / b = tensor([0.2787+0.0656j, 0.4690-0.0354j])
a ** 2 = tensor([-3.+4.j, -7.-24.j])
Conjugate of a: tensor([1.-2.j, 3.+4.j])
exp(a) = tensor([ -1.1312+2.4717j, -13.1288+15.2008j])
log(a) = tensor([0.8047+1.1071j, 1.6094-0.9273j])
